AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.shiyanlou.shinelon::Movie_Web
Resources:
  Movie_WebFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.shiyanlou.shinelon.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/Movie_Web-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  Movie_WebApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: Movie_WebApi
